# Generated by Django 3.2.2 on 2021-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('discription', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='images/products/')),
            ],
        ),
    ]
